enum ProfileActionTypes {
  FETCH_PROFILES_REQUEST = 'FETCH_PROFILES_REQUEST',
  FETCH_PROFILES_SUCCESS = 'FETCH_PROFILES_SUCCESS',
  FETCH_PROFILES_FAILURE = 'FETCH_PROFILES_FAILURE',
  SET_SELECTED_PROFILE = 'SET_SELECTED_PROFILE',
  SET_THEME = 'SET_THEME',
}
export default ProfileActionTypes;
